### PR TITLE
Feature/sound thread

### PR DESCRIPTION
**Pull request by FarisElghlan**
Added sound effects and background music to the game!
<feature,review

### CODE REVIEW

**Comment by JoshCode** [comment]
You committed merge conflicts

<review

**Comment by FarisElghlan** [comment]
Fixed merge conflicts.
<review

**Comment by JoshCode** [comment]
Please turn down the volume a bit for the music, can't test the rest now because of it's volume. Also please use a new thread for each sound effect, the game is sometimes very slow because of the sound effects.

<review

**Comment by FarisElghlan** [comment]
Changed to a different java sound player and made a separate thread for each sound effect.
<feature, review

**Comment by MHMCD** [comment]
Looks good and I didn't find any problems while testing
<review

**Pull request merged**
