### PR TITLE
Software metrics exercise

### PR DESCRIPTION
**Pull request by FarisElghlan**
This branch contains the answers to assignment 2 of sprint 4 (pdf) and all code changes which were necessary to finish this assignment.

Most notable code changes:
- There is now an AbstractLine class which is extended by Line and Projectile. It contains the method to calculate the intersection point. --> to solve "sibling duplication" inCode flaw.
- Some comments
- Some fields are made protected instead of public

<review

### CODE REVIEW

**Comment by MHMCD** [comment]
Looks good but I have 2 suggestions

1)

```
 public void updateLinePoints() {
    updateLinePoints(line);
 }
```

Since updateLinePoints() is only called twice in update and in the test method, wouldn't it more convenient to remove the whole method and change updateLinePoints() to updateLinePoints(line).

2)

Change the naming of the results to more convenient names (Metrics_Old, Metrics_New),  it makes it easier to distinguish the files.

edit: I indeed meant method instead of class

<review

**Comment by FarisElghlan** [comment]
OK I will remove the method (I guess you meant method instead of class. 
When I changed the name of the file, it wasn't visible in the list of snapshots of inCode. I didn't really test it wel, but because of this I decided to not rename the file. I think the numbers in the file name have a meaning (like the time at which it was made).
<review

**Comment by FarisElghlan** [comment]
Actually after looking at it in more detail the line object of the Projectile class is private, so it can't be accessed from the test class. If I change this part it will only become uglier.
<review

**Comment by MHMCD** [comment]
Then we will leave it like this.

<review

**Pull request merged**
