### PR TITLE
Fix/level redesign

### PR DESCRIPTION
**Pull request by JoshCode**
<feature

### CODE REVIEW

**Comment by FarisElghlan** [comment]
When playing the level a bug occurs when going to level 2. It has something to do with the door:
Caused by: nl.joshuaslik.tudelft.SEM.utility.xml.NoSuchElementException: door does not have element 'time_ns'
    at nl.joshuaslik.tudelft.SEM.utility.xml.XMLTag.getElement(XMLTag.java:159)
Please fix this before merging. It would also be nice if you could merge dev into your branch again, so I can check you branch with the recently added bug fixes.
<review

**Comment by FarisElghlan** [comment]
I think it would be better to have the xml package inside the model package instead of the utility package.
<review

**Comment by JoshCode** [comment]
I disagree, XML Parser and supporting classes are utility classes. They don't have anything to do with the game and don't belong in the model package.

Fixed the bug.

<review

**Comment by FarisElghlan** [comment]
There is still a bug when going to level 3:
Caused by: nl.joshuaslik.tudelft.SEM.utility.xml.NoSuchElementException: door does not have element 'remaining'
    at nl.joshuaslik.tudelft.SEM.utility.xml.XMLTag.getElement(XMLTag.java:159)

<review

**Comment by FarisElghlan** [comment]
The bubble door in level 3 should open when 2 bubbles are left (there are 2 bubbles right of the door). The rest looks good!
<review

**Pull request merged**
