### PR TITLE
Add buttons in GUI

### PR DESCRIPTION
**Pull request by lisv**
Added the buttons for classic and survival mode (survival mode button does not lead to anywhere yet as survival mode is not implemented yet)

<user-interface

### CODE REVIEW

**Comment by FarisElghlan** [comment]
When you don't move your mouse quick enough you are unable to use the play button. Also when clicking the play button, the options dissapear. Please resolve these issues first.
<review

**Comment by lisv** [comment]
These problems are now solved.

<user-interface

**Comment by FarisElghlan** [comment]
Please don't add the buttons to the classes variables if they aren't used:
@FXML
    private Button playButton, chooseLevelButton, optionsButton, quitButton, classicButton, survivalButton;
--> classicButton and survivalButton are not used and can be removed.
Otherwise this might generate inCode warnings. If you really want to add those 2 buttons to the files to show they are available, place a comment with the buttons names instead, so they are visible to the programmer and don't generate warnings.

Everything else looks nice!
<review

**Comment by lisv** [comment]
You are right. When I created them I thought I was going to use them later but that turned out to be not the case so I removed them just now.

<user-interface

**Pull request merged**
